# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldself', models.CharField(max_length=300, verbose_name='Insert Text Here')),
                ('fieldsignal', models.CharField(max_length=300, verbose_name='Do not touck it')),
            ],
        ),
    ]
